### PR TITLE
Upgrade to punycode 2.1

### LINKED ISSUE #82: Punycode AMD error with RequireJS
We get the following error TypeError: punycode.toASCII is not a function when using node request that uses this library, the problem is with punycode 1.4.1 which doesn't work with AMD. Please update dependencies to 2.0.1

Thank you

### PR DESCRIPTION
**Pull request by stash**
Fixes #82

### CODE REVIEW

**Comment by stash** [comment]
TravisCI test indicates that this seems to work with node >= 0.10.
