### ISSUE TITLE
v2.5.0 : str.trim() is not a function

### ISSUE THREAD

**Issue by willemotlucas** [salesforce/tough-cookie#132]
We're using tough-cookie ^2.4.3 (which actually installs 2.5.0) with request ^2.88.0.

This code worked with 2.4.3 : 
```
const cookiesJar = requestModule.jar();
 _.forEach(initialCookies, (cookie: Object) => {
 const newCookie = toughCookie.fromJSON(JSON.stringify(cookie));
 const hostUrl = `${initialOptions.protocol}//${initialOptions.host}/`;
 cookiesJar.setCookie(newCookie, hostUrl);
});
```

But we're getting the following error with 2.5.0 : 
```
TypeError: str.trim is not a function
 at Function.parse (node_modules/request/node_modules/tough-cookie/lib/cookie.js:429:13)
 at CookieJar.setCookie (node_modules/request/node_modules/tough-cookie/lib/cookie.js:1011:21)
 at CookieJar.setCookieSync (node_modules/request/node_modules/tough-cookie/lib/cookie.js:1402:18)
 at RequestJar.setCookie (node_modules/request/lib/cookies.js:25:20)
```

Any hint about what could cause this issue in 2.5.0?

Thanks!

**Comment by jmac105** [comment]
We're seeing the same issue

**Comment by gombosg** [comment]
Same here with the same setup. The cookie that looks like a `Cookie` instance from outside is not recognized on the inside.

**Comment by stash** [comment]
@willemotlucas @jmac105 @gombosg what environment are you using (node? browser? etc.?)

**Comment by gombosg** [comment]
Used Node 8, but I worked around the bug by converting the cookie into a cookie string and passing that to the library instead of an object.
The library fails at the `instanceof Cookie` part - even if the object is indeed a `Cookie` instance, the prototype constructor may have been different. (Does it matter if it's loaded from a different directory?)

**Comment by stash** [comment]
Thanks @gombosg.

`instanceof` definitely goes on an actual Function object, so if you have two functions named `Cookie` (the constructor), the `instanceof` and `==` and `===` operators will all return false.

FWIW, I'm able to reproduce this in a test now with request 2.88.0 and node 11.4.0. I'll look into it again later today.

**Comment by awaterma** [comment]
Thanks for looking into this @stash!

**Comment by tehnorm** [comment]
Noticed the same error when:

```
Cookie.parse(results.responseHeaders['set-cookie'])
```

In our case it ended up `results.responseHeaders['set-cookie']` was an array that needed to be iterated calling `Cookie.parse` on each element. Might be handy for `Cookie.parse()` check if the value it attempts to parse is a string?

Although, given the initial example this may not be related.

**Comment by legowerewolf** [comment]
I'm still seeing this with v3.0.1. 
```shell
$ npm ls --depth=0
+-- @types/commander@2.12.2
+-- @types/inquirer@6.0.3
+-- @types/node@12.0.10
+-- @types/request-promise-native@1.0.16
+-- @types/tough-cookie@2.3.5
+-- commander@2.20.0
+-- idx@2.5.6
+-- inquirer@6.4.1
+-- request@2.88.0
+-- request-promise-native@1.0.7
+-- tough-cookie@3.0.1
`-- typescript@3.5.2
```

**Comment by KevinGong2013** [comment]
<img width="1049" alt="Screen Shot 2019-08-30 at 4 25 08 PM" src="https://user-images.githubusercontent.com/5820203/64005489-1e1d6100-cb43-11e9-846e-a9bc1e3e420f.png">

typescript `(cookie instanceof Cookie)` return false.

@awaterma

**Comment by awaterma** [comment]
I'll take a look once I have a little time, probably over the weekend. We haven't had a release for a bit. We are working on closing out p/r to prepare for an update. Apologies for our tardiness. Pull request would also be appreciated to resolve the issue.

**Comment by ecdeveloper** [comment]
It's been almost a year :(

**Comment by awaterma** [comment]
This is a volunteer effort, with our focus on maintaining the codeline.

Pull Requests are always appreciated, and are what we focus on first. Please take a look at our contributor's agreement.

**Comment by awaterma** [comment]
I've assigned this to myself; I'll try and pick up when I can. Sorry for our delays.

**Comment by GabrielLomba** [comment]
@awaterma I just hit the exact same `instanceof Cookie` issue but in a different spot in the code.

`Cookiejar.serialize` tries to delete `creationIndex` prop after getting all cookies from the store [here](https://github.com/salesforce/tough-cookie/blob/dcfdd032332ece5e60b732f3371f5e08d9e20cef/lib/cookie.js#L1443) but the condition fails, causing it to try to delete the prop in the original `Cookie` object, raising a `TypeError: Cannot delete property 'creationIndex' of [object Object]`.

**Comment by awaterma** [comment]
Ill take a look! Thank you for the report!

**Comment by dsoegijono** [comment]
Tried upgrading to 4.0.0 and it still has this error. 😕

**Comment by awaterma** [comment]
Sorry to be slow on this; I'll put this issue onto our project board and will try and take a look as soon as we can.

**Comment by vipul24Task** [comment]
The same issue here.
i try to convert date to strtotime
strtotime("2020-06-18 01:51:31");

**Comment by awaterma** [comment]
Stash was able to reproduce this some time back with Request and Node 8; I'll see if I can add a unit test that reproduces this for us, so we can make some progress.

**Comment by PCAaron** [comment]
Tried upgrading to 4.0.0 and it still has this error,too.
used Node 8

**Comment by medelibero-sfdc** [comment]
@PCAaron can you paste in the latest error you are getting?

**Comment by awaterma** [comment]
I think we have a fix for this now; please take a look: https://github.com/salesforce/tough-cookie/pull/209

**Comment by GideonSenku** [comment]
![截屏2021-03-11 上午10 19 44](https://user-images.githubusercontent.com/39037656/110725884-4f581080-8253-11eb-85d2-69bdebb5e0a4.png)
Get same Error

**Comment by awaterma** [comment]
This should be closed in p/r #209.

If you can pull down the latest in Git (we haven't released these fixes to NPM yet), this issue should be resolved. If you are still seeing a similar issue, please open a new issue, hopefully with a reproducible test case, so we can take a look. 

Thank you!
